---
  - name: Add script.
    template: src=templates/http_logger.sh.j2 dest=/home/vagrant/http_logger.sh

  - name: Make the script executable.
    become: true
    file: dest=/home/vagrant/http_logger.sh mode=a+x
  
  - name: Add script to crontab.
    cron:
      name: "http_logger"
      minute: "0"
      job: "/home/vagrant/http_logger.sh"
...