---
  - name: Install apache2.
    become: yes
    apt: name=apache2 state=latest

  - name: Configure apache2 (1/4).
    become: yes
    template: src=templates/apache2.conf.j2 dest=/etc/apache2/apache2.conf

  - name: Configure apache2 (2/4).
    become: yes
    template: src=templates/ports.conf.j2 dest=/etc/apache2/ports.conf

  - name: Configure apache2 (3/4).
    become: yes
    template: src=templates/vhost.conf.j2 dest=/etc/apache2/sites-available/{{ item.name_server }}.conf
    with_items: "{{ websites }}"

  - name: Configure apache2 (4/4).
    become: yes
    file:
      src: /etc/apache2/sites-available/{{ item.name_server }}.conf
      dest: /etc/apache2/sites-enabled/{{ item.name_server }}.conf
      state: link
    with_items: "{{ websites }}"

  - name: Create websites directory.
    become: yes
    file:
      path: /var/www/{{ item.name_server }}
      state: directory
    with_items: "{{ websites }}"

  - name: Add the market website files.
    become: yes
    copy: src=index.html dest=/var/www/{{ websites[0].name_server }}/index.html

  - name: Restart apache2.
    become: yes
    service: name=apache2 state=restarted
 
...
