---
  - name: Installation HTTP_SERVER.
    become: yes
    apt: name=apache2 state=latest update_cache=yes

  - name: Configuration HTTP_SERVER (1/2).
    become: yes
    template: src=templates/apache2.conf.j2 dest=/etc/apache2/apache2.conf

  - name: Configuration HTTP_SERVER (2/2).
    become: yes
    template: src=templates/ports.conf.j2 dest=/etc/apache2/ports.conf

  - name: Create website directory
    become: yes
    file:
      path: /var/www/{{ item.name_server }}
      state: directory
    with_items: "{{ websites }}"

  - name: Copy the market website.
    become: yes
    copy: src=index.html dest=/var/www/{{ websites[0].name_server }}/index.html

  - name: Start HTTP_SERVER.
    become: yes
    service: name=apache2 state=restarted
 
...
