---
  #---- INSTALLATION HTML_BUILDER ----
  - name: Install python-setuptools.
    become: yes
    apt: name=python-setuptools state=latest

  - name: Clone csv2html.
    git:
      repo: 'https://github.com/dbohdan/csv2html.git'
      dest: ~/csv2html

  - name: Install csv2html.
    become: true
    shell: python setup.py install
    args:
      chdir: csv2html/

  - name: Add script.
    template: src=templates/html_builder.sh.j2 dest=/home/vagrant/html_builder.sh

  - name: Make the script executable.
    become: true
    file: dest=/home/vagrant/html_builder.sh mode=a+x

  - name: Add script to crontab.
    cron:
      name: "html_builder"
      minute: "*/5"
      job: "/home/vagrant/html_builder.sh"
...