---
  - name: Install dhcp-server.
    become: yes
    apt: name=isc-dhcp-server state=latest

  - name: Configure dhcp-server (1/2).
    become: yes
    template: src=templates/dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf

  - name: Configure dhcp-server (2/2).
    become: yes
    template: src=templates/isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server

  - name: Restart dhcp-server.
    become: yes
    service: name=isc-dhcp-server state=restarted
...
